#########################################
#     BungeeSafeguard Configuration     #
#            Version: 2.0               #
#          Author: Untitled             #
#########################################

version: "2.0"
whitelist-message: :( You are not whitelisted on this server
blacklist-message: :( We can't let you enter this server
enable-whitelist: true
# lazy-whitelist:
# - <lazy-whitelisted username, will be translated into UUID and moved to
#   whitelist>
lazy-whitelist:
# whitelist:
# - <whitelisted UUID>
whitelist:
enable-blacklist: false
# lazy-blacklist:
# - <lazy-blacklisted username, will be translated into UUID and moved to
#   blacklist>
lazy-blacklist:
# blacklist:
# - <banned UUID>
blacklist: