name: BungeeSafeguard
main: cyou.untitled.bungeesafeguard.BungeeSafeguardImpl
version: "3.1"
author: Untitled
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.20
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0
  - com.google.code.gson:gson:2.8.7
  - io.ktor:ktor-client-core:1.6.0
  - io.ktor:ktor-client-core-jvm:1.6.0  # Somehow, BungeeCord misses this
  - io.ktor:ktor-client-cio:1.6.0
  - io.ktor:ktor-client-cio-jvm:1.6.0  # Somehow, BungeeCord misses this